/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aluno;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 *
 * @author Everson Pereira e Leo
 */
public class Form extends JFrame {
    private List<Aluno> alunos;
    private JTextField campoNome;
    private JTextField campoIdade;
    private JTextField campoEndereco;
    
    /**
     * Creates new form form
     */
    public Form() {
        alunos = new ArrayList<>();

        setLayout(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);

        gbc.gridx = 0; gbc.gridy = 0;
        add(new JLabel("Nome:"), gbc);
        campoNome = new JTextField(20);
        gbc.gridx = 1; gbc.gridy = 0;
        add(campoNome, gbc);

        gbc.gridx = 0; gbc.gridy = 1;
        add(new JLabel("Idade:"), gbc);
        campoIdade = new JTextField(20);
        gbc.gridx = 1; gbc.gridy = 1;
        add(campoIdade, gbc);

        gbc.gridx = 0; gbc.gridy = 2;
        add(new JLabel("Endereço:"), gbc);
        campoEndereco = new JTextField(20);
        gbc.gridx = 1; gbc.gridy = 2;
        add(campoEndereco, gbc);

        JPanel panelBotoes = new JPanel(new GridLayout());
        JButton botaoOk = new JButton("Ok");
        botaoOk.addActionListener(e -> adicionarAluno());
        panelBotoes.add(botaoOk);

        JButton botaoLimpar = new JButton("Limpar");
        botaoLimpar.addActionListener(e -> limparCampos());
        panelBotoes.add(botaoLimpar);

        JButton botaoMostrar = new JButton("Mostrar");
        botaoMostrar.addActionListener(e -> mostrarAlunos());
        panelBotoes.add(botaoMostrar);

        JButton botaoSair = new JButton("Sair");
        botaoSair.addActionListener(e -> System.exit(0));
        panelBotoes.add(botaoSair);

        gbc.gridx = 0; gbc.gridy = 3; gbc.gridwidth = 2;
        add(panelBotoes, gbc);

        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(400, 180);
        setVisible(true);
    }
    
    private void adicionarAluno() {
        String nome = campoNome.getText();
        int idade = Integer.parseInt(campoIdade.getText());
        String endereco = campoEndereco.getText();

        alunos.add(new Aluno(endereco, idade, nome));
        limparCampos();
    }

    private void limparCampos() {
        campoNome.setText("");
        campoIdade.setText("");
        campoEndereco.setText("");
    }

    private void mostrarAlunos() {
        if (alunos.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nenhum aluno cadastrado.");
            return;
        }
        
        StringBuilder listaAlunos = new StringBuilder("Lista de Alunos:\n");
        for (Aluno aluno : alunos) {
            listaAlunos.append("Id: ").append(aluno.getUuid()).append(" Nome: ").append(aluno.getNome()).append("\n");
        }
        JOptionPane.showMessageDialog(this, listaAlunos.toString());
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
